/**
 * M8.1 — PushSimulator
 * Simulates a second-device "number-matching" push prompt.
 * Displays a 2-digit target code and 3 choice buttons (1 correct, 2 random decoys).
 * Calls onMatch(true) when the correct number is picked, onMatch(false) otherwise.
 *
 * "Phone" panel mirrors the authenticator screen; "login" panel is the browser.
 */
import { useMemo, useState } from 'react';

interface PushSimulatorProps {
  /** The correct 2-digit code (10–99) generated by LoginPage */
  targetCode: number;
  /** Fired with true if the user picks the right number, false otherwise */
  onMatch: (correct: boolean) => void;
  disabled?: boolean;
}

/** Generates two random decoy numbers that are distinct from targetCode */
function generateDecoys(target: number): [number, number] {
  const decoys: number[] = [];
  while (decoys.length < 2) {
    const n = 10 + Math.floor(Math.random() * 90); // 10–99
    if (n !== target && !decoys.includes(n)) decoys.push(n);
  }
  return [decoys[0], decoys[1]];
}

/** Fisher-Yates shuffle */
function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export default function PushSimulator({ targetCode, onMatch, disabled = false }: PushSimulatorProps) {
  // Choices are stable for this component instance
  const choices = useMemo(() => {
    const [d1, d2] = generateDecoys(targetCode);
    return shuffle([targetCode, d1, d2]);
  }, [targetCode]);

  const [picked, setPicked] = useState<number | null>(null);

  function handlePick(n: number) {
    if (disabled || picked !== null) return;
    setPicked(n);
    onMatch(n === targetCode);
  }

  const isCorrect = (n: number) => picked !== null && n === targetCode;
  const isWrong   = (n: number) => picked === n && n !== targetCode;

  return (
    <div className="flex flex-col gap-5 sm:flex-row sm:gap-6">

      {/* ── Left: Browser "Sign-in" panel ── */}
      <div className="flex-1 rounded-xl border border-border bg-surface-elevated p-5 flex flex-col gap-3">
        <p className="text-xs font-semibold uppercase tracking-widest text-ink-muted">
          Sign-in request
        </p>
        <p className="text-sm text-ink-secondary leading-relaxed">
          Check your authenticator and select the matching number.
        </p>
        <div className="mt-2 flex items-center justify-center rounded-lg bg-accent/10 border border-accent/30 py-5">
          <span
            className="font-mono text-4xl font-bold tracking-widest text-accent"
            aria-label={`Target code: ${targetCode}`}
          >
            {String(targetCode).padStart(2, '0')}
          </span>
        </div>
      </div>

      {/* ── Right: Simulated phone panel ── */}
      <div className="flex-1 rounded-xl border border-border bg-surface-subtle p-5 flex flex-col gap-4">
        <div className="flex items-center gap-2">
          <div className="h-1.5 w-1.5 rounded-full bg-success animate-pulse" />
          <p className="text-xs font-semibold uppercase tracking-widest text-ink-muted">
            📱 Authenticator (simulated)
          </p>
        </div>
        <p className="text-sm text-ink-secondary">
          TrustLine is requesting approval. Which number matches your screen?
        </p>

        {/* Choice buttons */}
        <div className="grid grid-cols-3 gap-3 mt-1">
          {choices.map((n) => {
            const base =
              'flex items-center justify-center rounded-lg border font-mono text-xl font-semibold py-4 transition-all duration-150';
            const state =
              picked === null
                ? 'border-border bg-surface-elevated text-ink-primary hover:border-accent hover:bg-accent/10 hover:text-accent cursor-pointer active:scale-95'
                : isCorrect(n)
                  ? 'border-success bg-success/10 text-success cursor-default'
                  : isWrong(n)
                    ? 'border-danger bg-danger/10 text-danger cursor-default'
                    : 'border-border bg-surface-elevated text-ink-muted opacity-50 cursor-default';

            return (
              <button
                key={n}
                id={`push-choice-${n}`}
                type="button"
                disabled={disabled || picked !== null}
                onClick={() => handlePick(n)}
                className={`${base} ${state}`}
                aria-label={`Choose number ${n}`}
              >
                {String(n).padStart(2, '0')}
              </button>
            );
          })}
        </div>

        {picked !== null && (
          <p
            className={`text-sm font-medium text-center mt-1 ${
              picked === targetCode ? 'text-success' : 'text-danger'
            }`}
          >
            {picked === targetCode
              ? '✓ Number matched — continue below'
              : '✗ Incorrect — please restart sign-in'}
          </p>
        )}
      </div>
    </div>
  );
}
